title: Prashik's Blogs
author: Prashik Dewtale
email: prashikdewtale69@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This Site is a my Blogging site which i am creating while learning on Github pages Deployment

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
